apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: 378505040508.dkr.ecr.us-east-1.amazonaws.com/python-redis-counter:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis.prod.svc.cluster.local"  
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT
