apiVersion: v1
kind: Service
metadata:
  name: counter-app-service
  namespace: prod
spec:
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

