---
- name: Install Jenkins on Ubuntu Server
  hosts: jenkins
  become: yes
  tasks:

    - name: Remove any previous Jenkins repo (debian-stable or others)
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null


    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      apt:
        name: default-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins
      service:
        name: jenkins
        state: started
        enabled: true

    - name: Allow Jenkins port 8080 through UFW
      ufw:
        rule: allow
        port: 8080
        proto: tcp
